* =monokaish-logseq=

My theme losely based on monokai. Only dark mode is configured.

** Installation

*** Online

Add =@import url('https://cdn.jsdelivr.net/gh/t4ccer/monokaish-logseq@main/custom.css');= to =custom.css= file in your logseq directory.

*** Offline

Copy content of =custom.css= file from this repo to =custom.css= file in your logseq directory.

** License

Copyright (C) 2022 Tomasz Maciosowski (t4ccer)

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
